// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU7zSsB8w_9MA8bNh4e9HvnC21_ac0LuI',
    appId: '1:1042193210346:web:f1b2411d8c68961834b093',
    messagingSenderId: '1042193210346',
    projectId: 'joritna',
    authDomain: 'joritna.firebaseapp.com',
    storageBucket: 'joritna.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8oMB6NzHvNcrXYp3ovWTlt9ZCrvQho_M',
    appId: '1:1042193210346:android:ccdfc39d243ac13e34b093',
    messagingSenderId: '1042193210346',
    projectId: 'joritna',
    storageBucket: 'joritna.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3Isj8T7It34uKcwo4DxgYpeQy_hUnMw0',
    appId: '1:1042193210346:ios:b6ca726b579194e834b093',
    messagingSenderId: '1042193210346',
    projectId: 'joritna',
    storageBucket: 'joritna.firebasestorage.app',
    iosBundleId: 'com.example.joritnaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3Isj8T7It34uKcwo4DxgYpeQy_hUnMw0',
    appId: '1:1042193210346:ios:b6ca726b579194e834b093',
    messagingSenderId: '1042193210346',
    projectId: 'joritna',
    storageBucket: 'joritna.firebasestorage.app',
    iosBundleId: 'com.example.joritnaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU7zSsB8w_9MA8bNh4e9HvnC21_ac0LuI',
    appId: '1:1042193210346:web:6b3d777da686025234b093',
    messagingSenderId: '1042193210346',
    projectId: 'joritna',
    authDomain: 'joritna.firebaseapp.com',
    storageBucket: 'joritna.firebasestorage.app',
  );
}
